### ISSUE TITLE
Unable to paste/auto fill login form

### ISSUE THREAD

**Issue by theLMGN** [weiran/Hackers#190] opened 2020-12-07 23:38 UTC
Hi. I’m trying to login to the app, however if I try to auto fill, the box to select the password manager is obscured by the login form. I also cannot paste into the password box

**Comment by weiran** [comment] 2020-12-21 12:53
Thanks for the report, it's an annoying one. 

Closing this as a dupe of #156.

**Closed by weiran** 2020-12-21 12:53 UTC
